addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"          % "0.1.14")
addSbtPlugin("io.spray"                  % "sbt-revolver"          % "0.9.1")
addSbtPlugin("com.eed3si9n"              % "sbt-assembly"          % "0.14.10")
addSbtPlugin("com.alejandrohdezma"       % "sbt-scalafmt-defaults" % "0.4.3")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"          % "2.4.3")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"         % "1.8.2")
